### ISSUE TITLE
VLAN ID in Bridge mode Uf-loco

### ISSUE THREAD

**Issue by tfdazevedo2** [Unifi-Tools/UFiber.Configurator#10]
Hello. First thank you for the initiative. You are the man. I have a Uf-loco and am trying to plug in a Zhone OLT to replace my ZNID-GPON-2426A1-EU. I can connect in Bridge mode, but I can't authenticate pppoe. I believe it is due to the lack of VLAN ID. Is it possible to implement this option in your software?
Thanks.

**Comment by galvesribeiro** [comment]
The VLan ID is not to be configured on UF-Loco. It should be configured on your router (EdgeRouter, USG, UDM, etc.). 

I have it configured on my UDM-Pro and it work just fine.
