### ISSUE TITLE
Compatibility with UFiber 4.4.9

### ISSUE THREAD

**Issue by cdalvaro** [Unifi-Tools/UFiber.Configurator#21]
Has anyone tried to update to ~[UFiber 4.4.8](https://community.ui.com/releases/UFiber-4-4-8/3773b6c8-ed78-4067-99f6-a14e0be31c24)~ [UFiber 4.4.9](https://community.ui.com/releases/UFiber-4-4-9/57ee4276-e0d9-4f21-9a33-9c708eecc98e) version?

If so, how was the process? There was any issue after the update?

Thank you in advance!

**Comment by neul0n** [comment]
I'm stuck as well - wondering if it's safe to upgrade it to the last version after has been patch or can I brick the device

**Comment by cdalvaro** [comment]
I just have updated my UFiber Nano G to [4.4.9](https://community.ui.com/releases/UFiber-4-4-9/57ee4276-e0d9-4f21-9a33-9c708eecc98e) and settings have preserved.

I'm getting IP from my ISP and everything is working fine, so I can say that updating is safe 🎉
