### ISSUE TITLE
Version v4.3.1

### ISSUE THREAD

**Issue by danndan23** [Unifi-Tools/UFiber.Configurator#9]
Hello,
Does it work with version 4.3.1? Anyone tried it?
Thank you.

**Comment by galvesribeiro** [comment]
Wasn't aware a new update came up. Just downloaded and applied to mine and re-ran the tool. I can confirm it worked. Please run a `--dry-run` first and see if it will report the appropriated data and then run a _real_ run to apply the changes.

**Comment by galvesribeiro** [comment]
I can confirm it can work on 4.3.1. Upgraded mine and it worked just fine.
